name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Check yarn is avaliable
    steps:
    - uses: actions/checkout@v2

    - name: Run yarn
      run: yarn add prettier
